services:
  backend:
    build: ./backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

